# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eScores' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for eScores
   pod 'GirdersSwift', '~> 0.4.2'
  target 'eScoresTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'eScoresUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
